### ISSUE TITLE
Tika Versions

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/mimir#2]
Is there a good reason why we exclude the tika transitive dependencies from gate-core and then depend on v1.5 directly?

Using a different version of tika can mean different behaviour in some of the format parsers, so I would assume we would always want to use the same format as the version of GATE itself (although I doubt we load anything directly other than GATE XML). Also using an old fixed number version means we don't get fixes (including security fixes) added to the newer versions.

**Comment by ianroberts** [comment]
Looking at the old Ivy dependency definition from Mimir 5.x it seems this was originally an attempt to exclude Tika's own multitude of transitive dependencies - we need the tika JAR itself in order to be able to initialise GATE (since some of the built in doc formats depend on it) but Mimir should never need to actually create its own `gate.Document` objects via the `Factory`, it only deserializes them from the request body in `indexDocuments` with an `ObjectInputStream`.

**Comment by ianroberts** [comment]
(Ivy lets you say `transitive="false"` on a dependency to completely exclude that dep's transitives, but in Maven you'd have to list all the exclusions individually by name)

**Comment by greenwoodma** [comment]
Looks like you can use * wildcards to exclude all transitive dependencies: https://stackoverflow.com/questions/547805/exclude-all-transitive-dependencies-of-a-single-dependency/7556707#7556707

**Comment by greenwoodma** [comment]
Looks as if this was closed by 003960cb8c7be5c73e3dd30ea4bb15b633b8c10e -- we now just use the version of Tika in gate-core without worrying about the transitive dependencies.
