### ISSUE TITLE
Remember and show index template name/template for index

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/mimir#9]
Once an index has been created, there seems to be no way to find out which index template has been used to create it. For documentation, it would be useful if the template name and template content would be kept and shown in the index admin page and/or (as read only data) the index edit page.

**Comment by greenwoodma** [comment]
The problem is that indexes can be moved from one mimir instance to another etc. and once created don't need access to the template. The template can also be edited after the index has been created, meaning a link between the two, even if possible, wouldn't be particularly useful.

All the information is, however, stored in the `config.xml` file that is part of the index. While it's a little more difficult to read it's not terrible. Maybe one option would be to add a link in the GUI to let people view the `config.xml` file without having to manually hunt it down on disk?

**Comment by greenwoodma** [comment]
I should also add that for some things the `config.xml` file is more useful than the index template as it explicitly details things that are assumed or hidden in the index template. A good example of this is what original markup annotations are preserved for formatting purposes.

**Comment by johann-petrak** [comment]
The config xml file is better than nothing and that additional info is interesting, but not too easy to work backwards to the template (but a template is needed to create an index, the config xml cannot be used, I think). 

I just wonder why not just store a copy of the original template that was used as part of the index? The effort for this is practically zero and it would make it really easy to figure out what was done and recreate the index or build on it. Also, that way any comments in the template code would get preserved. And again, the original need came from looking at a mimir server with dozens of indices and templates and trying to figure out which index was created with which template, I think making that easy discoverable would be useful and the effort to do it looks small.

**Comment by greenwoodma** [comment]
I guess one reason is that after an index has been created you can edit the `config.xml` to change certain things, at which point the index template would no longer match the index.

**Comment by ianroberts** [comment]
> I just wonder why not just store a copy of the original template that was used as part of the index?

Because it never occurred to us previously that it might have been useful.

> but a template is needed to create an index, the config xml cannot be used, I think

If you did happen to have a valid config.xml then you could put it in a directory on the mimir server and then "import an existing index" from that directory.

**Comment by johann-petrak** [comment]
The config xml file is better than nothing and that additional info is interesting, but not too easy to work backwards to the template. The template may contain valuable comments and is much more readable too. Since the effort to just store the original template in the directory is almost zero, I can see no problems and only advantages of doing this.

**Comment by ianroberts** [comment]
Maybe an acceptable compromise might be to have mimir-web put `original-template.groovy` and `original-config.xml` into the folder of any index it creates from scratch, with a generated comment at the top saying this is the _original_ template that was used when the index was created but config.xml may have been modified since - diff against original-config to check.

**Comment by johann-petrak** [comment]
That would be perfect and very helpful from my POV! 
TBH I did not know that modifying the config xml is something people actually do -- how does one know what can safely be changed and what would cause problems?

**Comment by ianroberts** [comment]
For “people” read me or Mark - it’s occasionally necessary to change things like the URL of a SPARQL endpoint, the precise cacheing characteristics of an H2 helper, or the definition of a MentionDescriber, but you can’t make big changes like renaming annotation types or changing features without it invalidating the rest of the index files anyway.
